/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '7/01/16 9:54' with Gradle 2.6
 *
 * @author mati, @date 7/01/16 9:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
